import {
  LayoutDashboard,
  Megaphone,
  Link as LinkIcon,
  Map,
  Info,
  Menu,
  LayoutTemplate,
  Users,
  GraduationCap,
  BookOpen,
  FileText,
  Image,
  Phone,
  Settings,
  PenTool,
  Calendar,
  CreditCard,
  UserCheck,
  ClipboardList
} from 'lucide-react';
import { MenuItem } from './types';

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    teachers: 'Teachers',
    employees: 'Employees',
    students: 'Students',
    academic: 'Academic',
    notice: 'Notice',
    gallery: 'Gallery',
    settings: 'Settings',
    logout: 'Logout',
    search: 'Search...',
    add: 'Add New',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    status: 'Status',
    actions: 'Actions',
    welcome: 'Welcome back, Admin',
    totalStudents: 'Total Students',
    totalTeachers: 'Total Teachers',
    activeNotices: 'Active Notices',
    themeControl: 'Theme & Colors',
    primaryColor: 'Primary Color',
    accentColor: 'Accent Color',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    selectLanguage: 'Select Language',
    name: 'Name',
    designation: 'Designation',
    phone: 'Phone',
    roll: 'Roll',
    class: 'Class',
    section: 'Section',
    
    // New Translations
    heroSection: 'Hero Section',
    logoTitle: 'Logo & Title',
    bannerCover: 'Banner & Cover',
    maps: 'Maps',
    aboutUs: 'About Us',
    staffManagement: 'Staff Management',
    chairmanMessage: 'Chairman Message',
    principalMessage: 'Principal Message',
    managingCommittee: 'Managing Committee',
    classRoutine: 'Class Routine',
    holidayList: 'Holiday List',
    admissionInfo: 'Admission Info',
    admissionForm: 'Admission Form',
    examNotices: 'Exam Notices',
    manualResult: 'Manual Result',
    onlineResult: 'Online Result',
    contactInfo: 'Contact Information',
    mainMenu: 'Main Menu',
    
    upload: 'Upload',
    update: 'Update',
    preview: 'Preview',
    clear: 'Clear',
    submit: 'Submit',
    approve: 'Approve',
    reject: 'Reject',
    view: 'View',
    remove: 'Remove',
    publish: 'Publish',
    addPhoto: 'Add Photo',
    
    title: 'Title',
    description: 'Description',
    messageBody: 'Message Body',
    photo: 'Photo',
    subject: 'Subject',
    teacher: 'Teacher',
    day: 'Day',
    period: 'Period',
    studentName: 'Student Name',
    fatherName: "Father's Name",
    motherName: "Mother's Name",
    dob: 'Date of Birth',
    address: 'Address',
    prevSchool: 'Previous School',
    guardianPhone: 'Guardian Phone',
    examName: 'Exam Name',
    gpa: 'GPA',
    grade: 'Grade',
    mobile: 'Mobile Number',
    email: 'Email Address',
    physicalAddress: 'Physical Address',
    geoLocation: 'Geo Location',
    joinDate: 'Join Date',
    menuTitle: 'Menu Title',
    urlLink: 'URL / Link',
    
    applicant: 'Applicant',
    applicationForm: 'Application Form',
    admissionRequests: 'Admission Requests',
    newAdmissionForm: 'New Admission Form',
    govtHoliday: 'Govt. Holiday',
    schoolHoliday: 'School Holiday',
    weekend: 'Weekend',
    upcomingHolidays: 'Upcoming Holidays',
    syncNational: 'Sync National Holidays',
    
    noData: 'No data found',
    underConstruction: 'Under Construction',
    underConstructionMsg: 'This section is part of the full dashboard architecture.',
    
    Sunday: 'Sunday',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    
    websiteTitle: 'Website Title',
    websiteLogo: 'Website Logo',
    applicationName: 'Application Name',
    saveTitle: 'Save Title',
    saveLogo: 'Save Logo',
    
    generalInfo: 'General Information',
    schoolName: 'School Name',
    academicYear: 'Academic Year',
    todaysDate: "Today's Date",
    systemStatus: 'System Status',
    totalRevenue: 'Total Revenue',
    classWiseData: 'Class Wise Data',
    
    resultName: 'Result Name',
    publishDate: 'Publish Date',
    pdfFile: 'PDF File',
    publishNewResult: 'Publish New Result',
    updateContact: 'Update Contact Details',
    saveChanges: 'Save Changes',
    mapConfiguration: 'Map Configuration',
    updateMap: 'Update Map',
    livePreview: 'Live Preview',
    brandColors: 'Brand Colors',
    appearance: 'Appearance',
    quickPresets: 'Quick Presets'
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    teachers: 'শিক্ষকবৃন্দ',
    employees: 'কর্মচারীবৃন্দ',
    students: 'শিক্ষার্থী',
    academic: 'একাডেমিক',
    notice: 'নোটিশ',
    gallery: 'গ্যালারি',
    settings: 'সেটিংস',
    logout: 'লগআউট',
    search: 'অনুসন্ধান...',
    add: 'নতুন যোগ করুন',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    status: 'অবস্থা',
    actions: 'কার্যকলাপ',
    welcome: 'স্বাগতম, অ্যাডমিন',
    totalStudents: 'মোট শিক্ষার্থী',
    totalTeachers: 'মোট শিক্ষক',
    activeNotices: 'সক্রিয় নোটিশ',
    themeControl: 'থিম এবং রং',
    primaryColor: 'প্রধান রং',
    accentColor: 'অ্যাকসেন্ট রং',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    language: 'ভাষা',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    name: 'নাম',
    designation: 'পদবী',
    phone: 'ফোন',
    roll: 'রোল',
    class: 'শ্রেণী',
    section: 'শাখা',

    // New Translations
    heroSection: 'হিরো সেকশন',
    logoTitle: 'লোগো এবং শিরোনাম',
    bannerCover: 'ব্যানার এবং কভার',
    maps: 'মানচিত্র',
    aboutUs: 'আমাদের সম্পর্কে',
    staffManagement: 'কর্মী ব্যবস্থাপনা',
    chairmanMessage: 'সভাপতির বাণী',
    principalMessage: 'প্রধান শিক্ষকের বাণী',
    managingCommittee: 'ব্যবস্থাপনা কমিটি',
    classRoutine: 'ক্লাস রুটিন',
    holidayList: 'ছুটির তালিকা',
    admissionInfo: 'ভর্তি তথ্য',
    admissionForm: 'ভর্তি ফরম',
    examNotices: 'পরীক্ষার নোটিশ',
    manualResult: 'ম্যানুয়াল ফলাফল',
    onlineResult: 'অনলাইন ফলাফল',
    contactInfo: 'যোগাযোগের তথ্য',
    mainMenu: 'প্রধান মেনু',

    upload: 'আপলোড',
    update: 'আপডেট',
    preview: 'প্রিভিউ',
    clear: 'মুছুন',
    submit: 'জমা দিন',
    approve: 'অনুমোদন',
    reject: 'বাতিল',
    view: 'দেখুন',
    remove: 'সরান',
    publish: 'প্রকাশ করুন',
    addPhoto: 'ছবি যোগ করুন',

    title: 'শিরোনাম',
    description: 'বিবরণ',
    messageBody: 'বার্তার মূল অংশ',
    photo: 'ছবি',
    subject: 'বিষয়',
    teacher: 'শিক্ষক',
    day: 'দিন',
    period: 'পিরিয়ড',
    studentName: 'শিক্ষার্থীর নাম',
    fatherName: "পিতার নাম",
    motherName: "মাতার নাম",
    dob: 'জন্ম তারিখ',
    address: 'ঠিকানা',
    prevSchool: 'পূর্ববর্তী স্কুল',
    guardianPhone: 'অভিভাবকের ফোন',
    examName: 'পরীক্ষার নাম',
    gpa: 'জিপিএ',
    grade: 'গ্রেড',
    mobile: 'মোবাইল নম্বর',
    email: 'ইমেল ঠিকানা',
    physicalAddress: 'শারীরিক ঠিকানা',
    geoLocation: 'জিও লোকেশন',
    joinDate: 'যোগদানের তারিখ',
    menuTitle: 'মেনু শিরোনাম',
    urlLink: 'URL / লিংক',

    applicant: 'আবেদনকারী',
    applicationForm: 'আবেদন ফরম',
    admissionRequests: 'ভর্তির অনুরোধ',
    newAdmissionForm: 'নতুন ভর্তির ফরম',
    govtHoliday: 'সরকারি ছুটি',
    schoolHoliday: 'স্কুল ছুটি',
    weekend: 'সাপ্তাহিক ছুটি',
    upcomingHolidays: 'আসন্ন ছুটির দিন',
    syncNational: 'জাতীয় ছুটি সিঙ্ক করুন',

    noData: 'কোন তথ্য পাওয়া যায়নি',
    underConstruction: 'নির্মাতা কাজ চলছে',
    underConstructionMsg: 'এই বিভাগটি সম্পূর্ণ ড্যাশবোর্ড আর্কিটেকচারের অংশ।',

    Sunday: 'রবিবার',
    Monday: 'সোমবার',
    Tuesday: 'মঙ্গলবার',
    Wednesday: 'বুধবার',
    Thursday: 'বৃহস্পতিবার',
    Friday: 'শুক্রবার',
    Saturday: 'শনিবার',

    websiteTitle: 'ওয়েবসাইট শিরোনাম',
    websiteLogo: 'ওয়েবসাইট লোগো',
    applicationName: 'অ্যাপ্লিকেশন নাম',
    saveTitle: 'শিরোনাম সংরক্ষণ করুন',
    saveLogo: 'লোগো সংরক্ষণ করুন',

    generalInfo: 'সাধারণ তথ্য',
    schoolName: 'স্কুলের নাম',
    academicYear: 'শিক্ষাবর্ষ',
    todaysDate: "আজকের তারিখ",
    systemStatus: 'সিস্টেম স্ট্যাটাস',
    totalRevenue: 'মোট আয়',
    classWiseData: 'শ্রেণী ভিত্তিক তথ্য',

    resultName: 'ফলাফলের নাম',
    publishDate: 'প্রকাশের তারিখ',
    pdfFile: 'পিডিএফ ফাইল',
    publishNewResult: 'নতুন ফলাফল প্রকাশ করুন',
    updateContact: 'যোগাযোগের বিবরণ আপডেট করুন',
    saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
    mapConfiguration: 'মানচিত্র কনফিগারেশন',
    updateMap: 'মানচিত্র আপডেট করুন',
    livePreview: 'লাইভ প্রিভিউ',
    brandColors: 'ব্র্যান্ডের রং',
    appearance: 'চেহারা',
    quickPresets: 'কুইক প্রিসেট'
  },
};

export const MENU_ITEMS: MenuItem[] = [
  { id: 'dashboard', label: 'Dashboard', labelBn: 'ড্যাশবোর্ড', icon: LayoutDashboard, path: '/' },
  { 
    id: 'hero', 
    label: 'Hero Section', 
    labelBn: 'হিরো সেকশন', 
    icon: LayoutTemplate,
    subItems: [
      { id: 'hero-logo', label: 'Logo & Title', labelBn: 'লোগো এবং শিরোনাম', path: '/hero/logo' },
      { id: 'hero-banner', label: 'Banner & Cover', labelBn: 'ব্যানার এবং কভার', path: '/hero/banner' },
    ]
  },
  { id: 'notice', label: 'Notices', labelBn: 'নোটিশ', icon: Megaphone, path: '/notice' },
  { id: 'main-menu', label: 'Main Menu', labelBn: 'প্রধান মেনু', icon: Menu, path: '/main-menu' },
  { id: 'maps', label: 'Maps', labelBn: 'মানচিত্র', icon: Map, path: '/maps' },
  { id: 'about', label: 'About Us', labelBn: 'আমাদের সম্পর্কে', icon: Info, path: '/about' },
  { 
    id: 'employees', 
    label: 'Staff Management', 
    labelBn: 'কর্মী ব্যবস্থাপনা', 
    icon: Users,
    subItems: [
      { id: 'emp-teachers', label: 'Teachers', labelBn: 'শিক্ষকবৃন্দ', path: '/teachers' },
      { id: 'emp-staff', label: 'Staff/Employees', labelBn: 'কর্মচারীবৃন্দ', path: '/staff' },
    ]
  },
  {
    id: 'academic',
    label: 'Academic',
    labelBn: 'একাডেমিক',
    icon: BookOpen,
    subItems: [
      { id: 'ac-message-chair', label: 'Chairman Message', labelBn: 'সভাপতির বাণী', path: '/academic/chairman-message' },
      { id: 'ac-message-principal', label: 'Principal Message', labelBn: 'প্রধান শিক্ষকের বাণী', path: '/academic/principal-message' },
      { id: 'ac-committee', label: 'Managing Committee', labelBn: 'ব্যবস্থাপনা কমিটি', path: '/academic/committee' },
      { id: 'ac-routine', label: 'Class Routine', labelBn: 'ক্লাস রুটিন', path: '/academic/routine' },
      { id: 'ac-holidays', label: 'Holiday List', labelBn: 'ছুটির তালিকা', path: '/academic/holidays' },
    ]
  },
  {
    id: 'students',
    label: 'Students Info',
    labelBn: 'শিক্ষার্থী তথ্য',
    icon: GraduationCap,
    subItems: [
      { id: 'st-6', label: 'Class Six', labelBn: '৬ষ্ঠ শ্রেণী', path: '/students/6' },
      { id: 'st-7', label: 'Class Seven', labelBn: '৭ম শ্রেণী', path: '/students/7' },
      { id: 'st-8', label: 'Class Eight', labelBn: '৮ম শ্রেণী', path: '/students/8' },
      { id: 'st-9', label: 'Class Nine', labelBn: '৯ম শ্রেণী', path: '/students/9' },
      { id: 'st-10', label: 'Class Ten', labelBn: '১০ম শ্রেণী', path: '/students/10' },
    ]
  },
  { 
    id: 'admission', 
    label: 'Admission', 
    labelBn: 'ভর্তি', 
    icon: UserCheck, 
    subItems: [
        { id: 'adm-info', label: 'Admission Info', labelBn: 'ভর্তি তথ্য', path: '/admission/info' },
        { id: 'adm-form', label: 'Admission Form', labelBn: 'ভর্তি ফরম', path: '/admission/form' },
    ]
  },
  { 
    id: 'exams', 
    label: 'Exams & Result', 
    labelBn: 'পরীক্ষা ও ফলাফল', 
    icon: FileText,
    subItems: [
        { id: 'ex-notice', label: 'Exam Notices', labelBn: 'পরীক্ষার নোটিশ', path: '/exams/notices' },
        { id: 'ex-result-manual', label: 'Manual Result', labelBn: 'ম্যানুয়াল ফলাফল', path: '/exams/manual-result' },
        { id: 'ex-result-online', label: 'Online Result', labelBn: 'অনলাইন ফলাফল', path: '/exams/online-result' },
    ]
  },
  { id: 'gallery', label: 'Gallery', labelBn: 'গ্যালারি', icon: Image, path: '/gallery' },
  { id: 'contact', label: 'Contact', labelBn: 'যোগাযোগ', icon: Phone, path: '/contact' },
  { id: 'settings', label: 'Settings', labelBn: 'সেটিংস', icon: Settings, path: '/settings' },
];