import {
  LayoutDashboard,
  Megaphone,
  Link as LinkIcon,
  Map,
  Info,
  Menu,
  LayoutTemplate,
  Users,
  GraduationCap,
  BookOpen,
  FileText,
  Image,
  Phone,
  Settings,
  PenTool,
  Calendar,
  CreditCard,
  UserCheck
} from 'lucide-react';
import { MenuItem } from './types';

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    teachers: 'Teachers',
    employees: 'Employees',
    students: 'Students',
    academic: 'Academic',
    notice: 'Notice',
    gallery: 'Gallery',
    settings: 'Settings',
    logout: 'Logout',
    search: 'Search...',
    add: 'Add New',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    status: 'Status',
    actions: 'Actions',
    welcome: 'Welcome back, Admin',
    totalStudents: 'Total Students',
    totalTeachers: 'Total Teachers',
    activeNotices: 'Active Notices',
    themeControl: 'Theme & Colors',
    primaryColor: 'Primary Color',
    accentColor: 'Accent Color',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    selectLanguage: 'Select Language',
    name: 'Name',
    designation: 'Designation',
    phone: 'Phone',
    roll: 'Roll',
    class: 'Class',
    section: 'Section',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    teachers: 'শিক্ষকবৃন্দ',
    employees: 'কর্মচারীবৃন্দ',
    students: 'শিক্ষার্থী',
    academic: 'একাডেমিক',
    notice: 'নোটিশ',
    gallery: 'গ্যালারি',
    settings: 'সেটিংস',
    logout: 'লগআউট',
    search: 'অনুসন্ধান...',
    add: 'নতুন যোগ করুন',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    status: 'অবস্থা',
    actions: 'কার্যকলাপ',
    welcome: 'স্বাগতম, অ্যাডমিন',
    totalStudents: 'মোট শিক্ষার্থী',
    totalTeachers: 'মোট শিক্ষক',
    activeNotices: 'সক্রিয় নোটিশ',
    themeControl: 'থিম এবং রং',
    primaryColor: 'প্রধান রং',
    accentColor: 'অ্যাকসেন্ট রং',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    language: 'ভাষা',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    name: 'নাম',
    designation: 'পদবী',
    phone: 'ফোন',
    roll: 'রোল',
    class: 'শ্রেণী',
    section: 'শাখা',
  },
};

export const MENU_ITEMS: MenuItem[] = [
  { id: 'dashboard', label: 'Dashboard', labelBn: 'ড্যাশবোর্ড', icon: LayoutDashboard, path: '/' },
  { 
    id: 'hero', 
    label: 'Hero Section', 
    labelBn: 'হিরো সেকশন', 
    icon: LayoutTemplate,
    subItems: [
      { id: 'hero-logo', label: 'Logo & Title', labelBn: 'লোগো এবং শিরোনাম', path: '/hero/logo' },
      { id: 'hero-banner', label: 'Banner & Cover', labelBn: 'ব্যানার এবং কভার', path: '/hero/banner' },
    ]
  },
  { id: 'notice', label: 'Notices', labelBn: 'নোটিশ', icon: Megaphone, path: '/notice' },
  { id: 'main-menu', label: 'Main Menu', labelBn: 'প্রধান মেনু', icon: Menu, path: '/main-menu' },
  { id: 'maps', label: 'Maps', labelBn: 'মানচিত্র', icon: Map, path: '/maps' },
  { id: 'about', label: 'About Us', labelBn: 'আমাদের সম্পর্কে', icon: Info, path: '/about' },
  { 
    id: 'employees', 
    label: 'Staff Management', 
    labelBn: 'কর্মী ব্যবস্থাপনা', 
    icon: Users,
    subItems: [
      { id: 'emp-teachers', label: 'Teachers', labelBn: 'শিক্ষকবৃন্দ', path: '/teachers' },
      { id: 'emp-staff', label: 'Staff/Employees', labelBn: 'কর্মচারীবৃন্দ', path: '/staff' },
    ]
  },
  {
    id: 'academic',
    label: 'Academic',
    labelBn: 'একাডেমিক',
    icon: BookOpen,
    subItems: [
      { id: 'ac-message-chair', label: 'Chairman Message', labelBn: 'সভাপতির বাণী', path: '/academic/chairman-message' },
      { id: 'ac-message-principal', label: 'Principal Message', labelBn: 'প্রধান শিক্ষকের বাণী', path: '/academic/principal-message' },
      { id: 'ac-committee', label: 'Managing Committee', labelBn: 'ব্যবস্থাপনা কমিটি', path: '/academic/committee' },
      { id: 'ac-routine', label: 'Class Routine', labelBn: 'ক্লাস রুটিন', path: '/academic/routine' },
      { id: 'ac-holidays', label: 'Holiday List', labelBn: 'ছুটির তালিকা', path: '/academic/holidays' },
    ]
  },
  {
    id: 'students',
    label: 'Students Info',
    labelBn: 'শিক্ষার্থী তথ্য',
    icon: GraduationCap,
    subItems: [
      { id: 'st-6', label: 'Class Six', labelBn: '৬ষ্ঠ শ্রেণী', path: '/students/6' },
      { id: 'st-7', label: 'Class Seven', labelBn: '৭ম শ্রেণী', path: '/students/7' },
      { id: 'st-8', label: 'Class Eight', labelBn: '৮ম শ্রেণী', path: '/students/8' },
      { id: 'st-9', label: 'Class Nine', labelBn: '৯ম শ্রেণী', path: '/students/9' },
      { id: 'st-10', label: 'Class Ten', labelBn: '১০ম শ্রেণী', path: '/students/10' },
    ]
  },
  { id: 'admission', label: 'Admission', labelBn: 'ভর্তি', icon: UserCheck, path: '/admission' },
  { id: 'exam', label: 'Exams & Result', labelBn: 'পরীক্ষা ও ফলাফল', icon: FileText, path: '/exams' },
  { id: 'gallery', label: 'Gallery', labelBn: 'গ্যালারি', icon: Image, path: '/gallery' },
  { id: 'contact', label: 'Contact', labelBn: 'যোগাযোগ', icon: Phone, path: '/contact' },
  { id: 'settings', label: 'Settings', labelBn: 'সেটিংস', icon: Settings, path: '/settings' },
];